# Generated by Django 2.0.2 on 2018-03-16 21:38

from django.db import migrations
from quartet_capture.migrations.loader import load_data


class Migration(migrations.Migration):
    dependencies = [
        ('quartet_capture', '0001_initial'),
    ]

    operations = [
        load_data()
    ]
