# Generated by Django 2.0.2 on 2018-06-05 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_capture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', help_text='The severity level of the message.', max_length=10, verbose_name='Severity Level')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='The time the task message was created.', verbose_name='Created Time')),
                ('message', models.TextField(help_text='The message data.', verbose_name='Message')),
                ('task', models.ForeignKey(help_text='The task that created the message.', on_delete=django.db.models.deletion.CASCADE, to='quartet_capture.Task', verbose_name='Task')),
            ],
        ),
    ]
