# Generated by Django 2.0 on 2018-10-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_capture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_class',
            field=models.CharField(help_text='The full python path to where the Step class is defined for example, mypackage.mymodule.MyStep', max_length=500, verbose_name='Class Path'),
        ),
    ]
