# Generated by Django 2.1.5 on 2019-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_capture', '0006_auto_20181223_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['name'], 'verbose_name': 'Filter'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['name'], 'verbose_name': 'Rule'},
        ),
        migrations.AddField(
            model_name='rulefilter',
            name='description',
            field=models.CharField(help_text='A short description of what this rule filter does.', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='rulefilter',
            name='name',
            field=models.CharField(help_text='The name of the rule filter.', max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
    ]
