# Generated by Django 2.0 on 2019-02-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_capture', '0007_auto_20190125_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['created'], 'verbose_name': 'Task History', 'verbose_name_plural': 'Task History'},
        ),
    ]
