# Generated by Django 2.0.2 on 2019-05-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_capture', '0008_auto_20190214_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmessage',
            options={'ordering': ['created'], 'verbose_name': 'Task Message', 'verbose_name_plural': 'Task Messages'},
        ),
    ]
