# Generated by Django 3.1.4 on 2021-03-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_capture', '0010_auto_20200401_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='The unique name of the job- autogenerated.', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Name'),
        ),
    ]
